package com.wm.bfd.oo.yaml;

public class Constants {

  /**
   * Global config
   */
  // final public static String TEMPLATE = "/etc/oneops-tool-bfd/yarn.yaml";
  final public static String TEMPLATE =
      "/Users/rzhan33/Documents/Ray/Projects/Swifthadoop/bfd-oneops-automation/resource/yarn.yaml";
  final public static String IP_OUTPUT = "json";
  final public static String DESCRIPTION = "GENERATED BY BOO. DO NOT MODIFY MANUALLY!";
  final public static String PLATFORMS = "platforms";
  final public static String EXTRACT = "extract";
  final public static String VARIABLES = "variables";
  final public static String DESCRIPTIONS = "description";
  final public static String YAML_ERROR = "The template file not found or has wrong format!";

  // Components
  final public static String USER = "user";

  // Operate
  final public static String DEPLOYMENT_ID = "deploymentId";
  final public static String DEPLOYMENT_STATE = "deploymentState";
}
