package com.wm.bfd.oo.yaml;

public class Constants {

  /**
   * Global config
   */
  final public static String TEMPLATE = "/test.yaml";
  final public static String IP_OUTPUT = "json";
  final public static String DESCRIPTION = "GENERATED BY BOO. DO NOT MODIFY MANUALLY!";
  final public static String PLATFORMS = "platforms";
  final public static String EXTRACT = "extract";
  final public static String VARIABLES = "variables";
  final public static String DESCRIPTIONS = "description";
  final public static String YAML_ERROR = "The template file not found or has wrong format!";
  final public static String AVAILABILITY = "availability";
  final public static String GLOBAL_DNS = "global_dns";
  final public static String SUBDOMAIN = "subdomain";
  final public static String ENV_NAME = "environment_name";
  final public static String TRUE = "true";


  final public static String BFD_TOOL = "The tool is managed by BFD team.";
  final public static String NO_AVAILABILITY = "You don't set the availability, please check your yaml config.";

  // Components
  final public static String USER = "user";

  // Operate
  final public static String DEPLOYMENT_ID = "deploymentId";
  final public static String DEPLOYMENT_STATE = "deploymentState";
}
